#!/bin/sh
echo 'this script assumes that the jenkins machine (or container) has python3, easy_install, and virtualenv already installed'
echo 'to do this run the following commands on the jenkins box:'
echo '        apt-get install python3'
echo '        apt-get install python3-setuptools'
echo '        apt-get install python3-pip'
echo '        apt-get install virtualenv'
echo '        apt-get install python3-venv'
echo '        apt-get install libxml2-dev libxslt-dev python-dev'
echo '        apt-get install python3-lxml python-lxml'


if [ "$(uname)" != "Darwin" ]; then
  python3 -m venv env
else
	python3.9 -m venv env
fi
env/bin/python --version
env/bin/python -m pip install --upgrade pip
env/bin/python -m pip install wheel
env/bin/python -m pip install flask
env/bin/python -m pip install requests
env/bin/python -m pip install Flask-APScheduler
if [ "$(uname)" != "Darwin" ]; then
  env/bin/python -m pip install --no-index --find-links file:///home/pi/libs/ifaddr-0.1.6-py3-none-any.whl --trusted-host file:///home/pi/libs/ifaddr-0.1.6-py3-none-any.whl ifaddr==0.1.6
else
  env/bin/python -m pip install ifaddr==0.1.6
fi
env/bin/python -m pip install lxml
if [ "$(uname)" != "Darwin" ]; then
  env/bin/python -m pip install --no-index --find-links file:///home/pi/libs/pywemo-0.4.46-py2.py3-none-any.whl --trusted-host file:///home/pi/libs/pywemo-0.4.46-py2.py3-none-any.whl pywemo
else
  env/bin/python -m pip install pywemo
fi


if [ "$(uname)" != "Darwin" ]; then
	env/bin/python -m pip install rpi.gpio
fi