#!/bin/sh

echo 'starting mock server'
if [ "$(uname)" == "Darwin" ]; then
	echo 'on Mac - running: ./env-setup/run-mock-my-house-server &'
    ./env-setup/run-mock-my-house-server &
else
	echo 'on non-Mac - running: setsid ./env-setup/run-mock-my-house-server < /dev/zero &> mock-server-log.txt &'
    setsid ./env-setup/run-mock-my-house-server < /dev/zero &> mock-server-log.txt &
fi

echo 'running tests'
env/bin/py.test ./test -s

echo 'shutting down mock server'
./env-setup/stop-mock-my-house-server
