#!/bin/sh

chmod a+x ./mock_services/mock_my_house_server.py
./mock_services/mock_my_house_server.py &

chmod a+x ./mock_services/mock_thermostat_server.py
./mock_services/mock_thermostat_server.py &
