#!/bin/sh
echo 'this script assumes that the jenkins machine (or container) has killall already installed'
echo 'to do this run the following commands on the jenkins box:'
echo '        apt-get install psmisc'

if [ "$(uname)" == "Darwin" ]; then
	echo 'on Mac - running: killall Python'
  killall Python
else
	echo 'on non-Mac - running: killall python'
    killall python
fi
